[package]
name = "tadpole-os"
version = "1.1.463"
description = "Tadpole OS Desktop App"
authors = ["DDS-Solutions"]
edition = "2024"
license = "MIT"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.5", features = [] }
tauri-plugin-shell = "2.3.5"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
chrono = "0.4.45"
rand = { version = "0.9.5", features = ["os_rng"] }
dotenvy = "0.15"

[profile.release]
panic = "abort" # Strip expensive panic hook
codegen-units = 16 # Parallelize compilation across cores
opt-level = "s" # Optimize for binary size
lto = "thin" # Parallelized ThinLTO for fast builds
strip = true # Remove all symbols
