/**
 * @docs ARCHITECTURE:TestSuites
 *
 * ### AI Context Alignment
 * - **Subsystem**: Frontend State Store / sovereign_store.test
 *
 * ### ⚠️ Invariants & Non-Negotiables
 * - `[Structural]` Store mutations maintain immutable state transitions and notify subscribers deterministically.
 *
 * ### 🔍 Debugging & Observability
 * - **Local Errors**: none
 * - **Telemetry Targets**: none declared
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { use_sovereign_store } from './sovereign_store';

const mock_decide_oversight = vi.fn().mockResolvedValue(undefined);

vi.mock('../services/system_api_service', () => ({
    system_api_service: {
        oversight: {
            decide_oversight: (...args: any[]) => mock_decide_oversight(...args)
        }
    }
}));

describe('use_sovereign_store', () => {
    beforeEach(() => {
        // Reset state
        use_sovereign_store.setState({
            messages: [],
            message_index_by_id: {},
            active_scope: 'agent',
            selected_agent_id: null,
            target_agent: 'Agent of Nine',
            target_cluster: '',
            is_detached: false,
        });
        
        // Mock UUID if not in high quality environment
        vi.stubGlobal('crypto', {
             randomUUID: () => 'mock-uuid-1234'
        });
    });

    afterEach(() => {
        vi.unstubAllGlobals();
    });

    it('has the correct default state', () => {
        const state = use_sovereign_store.getState();
        expect(state.messages).toEqual([]);
        expect(state.active_scope).toBe('agent');
        expect(state.target_agent).toBe('Agent of Nine');
        expect(state.is_detached).toBe(false);
    });

    describe('add_message', () => {
        it('adds a new message with autogenerated id and timestamp', () => {
            const store = use_sovereign_store.getState();
            store.add_message({
                sender_id: 'sys',
                sender_name: 'System',
                text: 'Hello Team',
                scope: 'agent'
            });

            const state = use_sovereign_store.getState();
            expect(state.messages).toHaveLength(1);
            expect(state.messages[0].text).toBe('Hello Team');
            expect(state.messages[0].id).toBe('mock-uuid-1234');
            expect(state.messages[0].timestamp).toBeDefined();
        });

        it('deduplicates messages with the same id', () => {
            const store = use_sovereign_store.getState();
            const msg = {
                id: 'fixed-123',
                sender_id: 'sys',
                sender_name: 'System',
                text: 'Hello Team',
                scope: 'agent' as const
            };

            store.add_message(msg);
            store.add_message(msg); // Attempt to add same ID again

            const state = use_sovereign_store.getState();
            expect(state.messages).toHaveLength(1);
        });
    });

    describe('Setters', () => {
        it('sets active scope', () => {
            const store = use_sovereign_store.getState();
            store.set_scope('cluster');
            expect(use_sovereign_store.getState().active_scope).toBe('cluster');
        });

        it('sets selected agent id', () => {
            const store = use_sovereign_store.getState();
            store.set_selected_agent_id('agent-id-99');
            expect(use_sovereign_store.getState().selected_agent_id).toBe('agent-id-99');
        });

        it('sets target agent', () => {
            const store = use_sovereign_store.getState();
            store.set_target_agent('DevOps Bot');
            expect(use_sovereign_store.getState().target_agent).toBe('DevOps Bot');
        });

        it('sets target cluster', () => {
            const store = use_sovereign_store.getState();
            store.set_target_cluster('Engineering_Alpha');
            expect(use_sovereign_store.getState().target_cluster).toBe('Engineering_Alpha');
        });

        it('sets is_detached', () => {
            const store = use_sovereign_store.getState();
            store.set_detached(true);
            expect(use_sovereign_store.getState().is_detached).toBe(true);
        });
    });

    describe('clear_history', () => {
        it('clears all messages from the store', () => {
            const store = use_sovereign_store.getState();
            store.add_message({
                sender_id: 'sys',
                sender_name: 'System',
                text: 'Sweep me',
                scope: 'agent'
            });

            expect(use_sovereign_store.getState().messages).toHaveLength(1);
            
            store.clear_history();
            expect(use_sovereign_store.getState().messages).toHaveLength(0);
        });
    });

    describe('update_message and append_message_part', () => {
        it('updates an existing message', () => {
            const store = use_sovereign_store.getState();
            store.add_message({ id: 'm1', sender_id: 's1', sender_name: 'A', text: 'hi', scope: 'agent' });
            store.update_message('m1', { text: 'updated' });
            
            const msg = use_sovereign_store.getState().get_message_by_id('m1');
            expect(msg?.text).toBe('updated');
        });

        it('appends a part to a message', () => {
            const store = use_sovereign_store.getState();
            store.add_message({ id: 'm1', sender_id: 's1', sender_name: 'A', text: 'hi', scope: 'agent' });
            const success = store.append_message_part('m1', { type: 'text', content: ' more' });
            
            expect(success).toBe(true);
            const msg = use_sovereign_store.getState().get_message_by_id('m1');
            expect(msg?.parts).toHaveLength(2); // Initial text part + new part
        });

        it('returns false when appending to non-existent message', () => {
            const store = use_sovereign_store.getState();
            const success = store.append_message_part('invalid', { type: 'text', content: 'test' });
            expect(success).toBe(false);
        });
    });

    describe('get_message_by_id', () => {
        it('retrieves a message by id', () => {
            const store = use_sovereign_store.getState();
            store.add_message({ id: 'm1', sender_id: 's1', sender_name: 'A', text: 'hi', scope: 'agent' });
            expect(store.get_message_by_id('m1')).toBeDefined();
            expect(store.get_message_by_id('m2')).toBeUndefined();
        });
    });

    describe('Cross-Tab Synchronization (BroadcastChannel)', () => {
        it('synchronizes ADD_MESSAGE events', async () => {
            
            // BroadcastChannel is mocked in setup.ts. 
            // We need to trigger the onmessage handler of the channel used by the store.
            // In a real scenario, this would happen via the channel instance.
            // Since we don't have direct access to the private chat_channel, 
            // we'll use a hack or verify the effect of postMessage if it was circular.
            // Actually, the store instance is created once.
            
            // Let's use a simpler approach: test that actions emit to the channel.
            const store = use_sovereign_store.getState();
            const spy = vi.spyOn(BroadcastChannel.prototype, 'postMessage');
            
            store.add_message({ id: 'm-sync', sender_id: 's1', sender_name: 'A', text: 'sync', scope: 'agent' });
            expect(spy).toHaveBeenCalledWith(expect.objectContaining({ type: 'ADD_MESSAGE' }));
            spy.mockRestore();
        });

        it('synchronizes SET_SCOPE events', () => {
            const store = use_sovereign_store.getState();
            const spy = vi.spyOn(BroadcastChannel.prototype, 'postMessage');
            store.set_scope('swarm');
            expect(spy).toHaveBeenCalledWith({ type: 'SET_SCOPE', payload: 'swarm' });
            spy.mockRestore();
        });
    });

    describe('Execution Metrics & User Question', () => {
        it('sets and updates execution metrics', () => {
            const store = use_sovereign_store.getState();
            expect(store.latest_metrics).toBeNull();

            store.set_execution_metrics({
                turns: 3,
                tool_calls_attempted: 5,
                tool_calls_failed: 1,
                cached_reads_hit: 2,
                files_modified_count: 4,
                total_input_tokens: 1200,
                total_output_tokens: 800,
                peak_context_tokens: 4500,
                total_cost_micro_usd: 15000,
                total_summarizations: 3,
                total_sub_agents: 1,
                excessive_summarization_warning: true
            });

            expect(use_sovereign_store.getState().latest_metrics?.turns).toBe(3);
            expect(use_sovereign_store.getState().latest_metrics?.excessive_summarization_warning).toBe(true);
        });

        it('resolves a pending user question and marks it answered', async () => {
            const store = use_sovereign_store.getState();
            store.add_message({
                id: 'q-msg',
                sender_id: 'agent-1',
                sender_name: 'Architect',
                agent_id: 'agent-1',
                text: 'Which database should we use?',
                scope: 'agent',
                parts: [{
                    type: 'question',
                    question_id: 'q-entry-1',
                    question: 'Which database should we use?',
                    options: ['PostgreSQL', 'SQLite'],
                    status: 'pending'
                }]
            });

            await store.resolve_user_question('q-entry-1', 'PostgreSQL');

            const updated_q = store.get_message_by_id('q-msg');
            expect(updated_q?.parts?.[0]).toMatchObject({
                type: 'question',
                status: 'answered',
                selected_option: 'PostgreSQL'
            });

            // Verify operator message was also added to chat
            const last_msg = use_sovereign_store.getState().messages.slice(-1)[0];
            expect(last_msg.sender_id).toBe('0');
            expect(last_msg.text).toBe('PostgreSQL');
            expect(mock_decide_oversight).toHaveBeenCalledWith('q-entry-1', 'approved', 'PostgreSQL');
        });

        it('reverts question status to pending if oversight decision fails', async () => {
            mock_decide_oversight.mockRejectedValueOnce(new Error('Network error'));
            const store = use_sovereign_store.getState();
            store.add_message({
                id: 'q-fail-msg',
                sender_id: 'agent-1',
                sender_name: 'Architect',
                agent_id: 'agent-1',
                text: 'Deploy to prod?',
                scope: 'agent',
                parts: [{
                    type: 'question',
                    question_id: 'q-fail-entry',
                    question: 'Deploy to prod?',
                    options: ['Deploy', 'Cancel'],
                    status: 'pending'
                }]
            });

            await store.resolve_user_question('q-fail-entry', 'Deploy');

            const updated_q = store.get_message_by_id('q-fail-msg');
            expect(updated_q?.parts?.[0]).toMatchObject({
                type: 'question',
                status: 'pending',
                selected_option: undefined
            });

            // Verify optimistic operator message was removed
            const operator_msg = use_sovereign_store.getState().messages.find(m => m.text === 'Deploy');
            expect(operator_msg).toBeUndefined();
        });

        it('maps answer to rejected when answering a non-approve option', async () => {
            const store = use_sovereign_store.getState();
            store.add_message({
                id: 'q-reject-msg',
                sender_id: 'agent-1',
                sender_name: 'Architect',
                agent_id: 'agent-1',
                text: 'Deploy?',
                scope: 'agent',
                parts: [{
                    type: 'question',
                    question_id: 'q-reject-entry',
                    question: 'Deploy?',
                    options: ['Approve', 'Reject'],
                    approve_option: 'Approve',
                    status: 'pending'
                }]
            });

            await store.resolve_user_question('q-reject-entry', 'Reject');
            expect(mock_decide_oversight).toHaveBeenCalledWith('q-reject-entry', 'rejected', 'Reject');
        });

        it('supports reference-counted initialize_sync_listeners without premature cleanup', () => {
            const store = use_sovereign_store.getState();
            const unmount1 = store.initialize_sync_listeners();
            const unmount2 = store.initialize_sync_listeners();

            // First unmount should NOT clear listeners
            unmount1();
            
            // Second unmount cleans up
            unmount2();
            // Idempotent call doesn't throw or go negative
            unmount2();
        });
    });
});
