/**
 * @file sovereignStore.test.ts
 * @description Suite for the local 'Sovereign' multi-agent chat and coordination.
 * @module Stores/SovereignStore
 * @testedBehavior
 * - Coordination: Scoping messages to specific agents or entire clusters.
 * - Integrity: Deduplication of messages based on unique event IDs.
 * - Detachment: Managing the UI state for popped-out command consoles.
 * @aiContext
 * - Mocks BroadcastChannel and crypto.randomUUID for a stable test environment.
 * - Asserts on message timestamps and internal ID generation.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { use_sovereign_store } from './sovereign_store';

// Mock Broadcast Channel API for test environment
class MockBroadcastChannel {
    name: string;
    onmessage: ((ev: MessageEvent) => void) | null = null;
    messages: any[] = [];
    
    constructor(name: string) {
        this.name = name;
    }

    postMessage(data: any) {
        this.messages.push(data);
    }
    
    close() {}
}

const mockChannel = new MockBroadcastChannel('test-channel');

vi.stubGlobal('BroadcastChannel', vi.fn().mockImplementation(() => mockChannel));
// Note: We simulate `chatChannel?.postMessage` behavior because the singleton 
// instantiated in store on load grabs a specific instance.
// For the sake of deep testing Zustand logic without fighting the imported singleton const, 
// we test the store mutations directly.

describe('use_sovereign_store', () => {
    beforeEach(() => {
        // Reset state
        use_sovereign_store.setState({
            messages: [],
            messageIndexById: {},
            activeScope: 'agent',
            selectedAgentId: null,
            targetAgent: 'Agent of Nine',
            targetCluster: '',
            isDetached: false,
        });
        mockChannel.messages = [];
        
        // Mock UUID if not in high quality environment
        vi.stubGlobal('crypto', {
             randomUUID: () => `mock-uuid-${Math.random()}`
        });
    });

    afterEach(() => {
        vi.unstubAllGlobals();
    });

    it('has the correct default state', () => {
        const state = use_sovereign_store.getState();
        expect(state.messages).toEqual([]);
        expect(state.activeScope).toBe('agent');
        expect(state.targetAgent).toBe('Agent of Nine');
        expect(state.isDetached).toBe(false);
    });

    describe('addMessage', () => {
        it('adds a new message with autogenerated id and timestamp', () => {
            const store = use_sovereign_store.getState();
            store.addMessage({
                senderId: 'sys',
                senderName: 'System',
                text: 'Hello Team',
                scope: 'agent'
            });

            const state = use_sovereign_store.getState();
            expect(state.messages).toHaveLength(1);
            expect(state.messages[0].text).toBe('Hello Team');
            expect(state.messages[0].id).toBeDefined();
            expect(state.messages[0].timestamp).toBeDefined();
        });

        it('deduplicates messages with the same id', () => {
            const store = use_sovereign_store.getState();
            const msg = {
                id: 'fixed-123',
                senderId: 'sys',
                senderName: 'System',
                text: 'Hello Team',
                scope: 'agent' as const
            };

            store.addMessage(msg);
            store.addMessage(msg); // Attempt to add same ID again

            const state = use_sovereign_store.getState();
            expect(state.messages).toHaveLength(1);
        });
    });

    describe('Setters', () => {
        it('sets active scope', () => {
            const store = use_sovereign_store.getState();
            store.setScope('cluster');
            expect(use_sovereign_store.getState().activeScope).toBe('cluster');
        });

        it('sets selected agent id', () => {
            const store = use_sovereign_store.getState();
            store.setSelectedAgentId('agent-id-99');
            expect(use_sovereign_store.getState().selectedAgentId).toBe('agent-id-99');
        });

        it('sets target agent', () => {
            const store = use_sovereign_store.getState();
            store.setTargetAgent('DevOps Bot');
            expect(use_sovereign_store.getState().targetAgent).toBe('DevOps Bot');
        });

        it('sets target cluster', () => {
            const store = use_sovereign_store.getState();
            store.setTargetCluster('Engineering_Alpha');
            expect(use_sovereign_store.getState().targetCluster).toBe('Engineering_Alpha');
        });

        it('sets isDetached', () => {
            const store = use_sovereign_store.getState();
            store.setDetached(true);
            expect(use_sovereign_store.getState().isDetached).toBe(true);
        });
    });

    describe('clearHistory', () => {
        it('clears all messages from the store', () => {
            const store = use_sovereign_store.getState();
            store.addMessage({
                senderId: 'sys',
                senderName: 'System',
                text: 'Sweep me',
                scope: 'agent'
            });

            expect(use_sovereign_store.getState().messages).toHaveLength(1);
            
            store.clearHistory();
            expect(use_sovereign_store.getState().messages).toHaveLength(0);
        });
    });
});


